#The prefix that will be sent in messages.
Prefix: '&c&lPrefix &8&l> &7'

#Here you can set if the message will be send or not. -> true/false !
BypassMessage: true

#The format for the message when the player joins the server.
Message_Format: '&aYou have succesfully bypassed the slots.'

#The permission for a player to bypass the commands.
BypassPermission: 'bypass.slots'